# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_ecs_cluster.de-2-1-ecs:
resource "aws_ecs_cluster" "de-2-1-ecs" {
  name = "de-2-1-ecs"
  tags = {
    "Team" = "DE-2-1"
  }
  tags_all = {
    "Team" = "DE-2-1"
  }

  configuration {
    execute_command_configuration {
      logging = "DEFAULT"
    }
  }

  service_connect_defaults {
    namespace = "arn:aws:servicediscovery:us-west-2:862327261051:namespace/ns-vavggcs4mf7ynae2"
  }

  setting {
    name  = "containerInsights"
    value = "disabled"
  }
}
