# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_ecs_cluster_capacity_providers.de-2-1-ecs:
resource "aws_ecs_cluster_capacity_providers" "de-2-1-ecs" {
  capacity_providers = [
    "FARGATE",
    "FARGATE_SPOT",
  ]
  cluster_name = aws_ecs_cluster.de-2-1-ecs.name
}
