# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_ecs_service.de-2-1-ecs__de-2-1-airflow:
resource "aws_ecs_service" "de-2-1-ecs__de-2-1-airflow" {
  cluster                            = aws_ecs_cluster.de-2-1-ecs.arn
  deployment_maximum_percent         = 200
  deployment_minimum_healthy_percent = 100
  desired_count                      = 1
  enable_ecs_managed_tags            = true
  enable_execute_command             = false
  health_check_grace_period_seconds  = 0
  name                               = "de-2-1-airflow"
  platform_version                   = "LATEST"
  propagate_tags                     = "SERVICE"
  scheduling_strategy                = "REPLICA"
  tags = {
    "Team" = "DE-2-1"
  }
  tags_all = {
    "Team" = "DE-2-1"
  }
  task_definition = aws_ecs_task_definition.de-2-1-airflow_31.arn
  triggers        = {}

  capacity_provider_strategy {
    base              = 0
    capacity_provider = "FARGATE"
    weight            = 1
  }

  deployment_circuit_breaker {
    enable   = true
    rollback = true
  }

  deployment_controller {
    type = "ECS"
  }

  network_configuration {
    assign_public_ip = true
    security_groups = [
      data.aws_security_group.sg-072d3f5641460e8b5.id,
    ]
    subnets = [
      aws_subnet.subnet-02fa7ecfdea40408e.id,
    ]
  }
}
