# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_cloudwatch_log_group._ecs_de-2-1-airflow:
resource "aws_cloudwatch_log_group" "_ecs_de-2-1-airflow" {
  name              = "/ecs/de-2-1-airflow"
  retention_in_days = 0
  tags              = {}
  tags_all          = {}
}
