# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_instance_profile.EMR_EC2_DefaultRole:
resource "aws_iam_instance_profile" "EMR_EC2_DefaultRole" {
  name     = "EMR_EC2_DefaultRole"
  path     = "/"
  role     = aws_iam_role.r-EMR_EC2_DefaultRole.name
  tags     = {}
  tags_all = {}
}
