# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role.r-EMR_EC2_DefaultRole:
resource "aws_iam_role" "r-EMR_EC2_DefaultRole" {
  assume_role_policy = jsonencode(
    {
      Statement = [
        {
          Action = "sts:AssumeRole"
          Effect = "Allow"
          Principal = {
            Service = "ec2.amazonaws.com"
          }
          Sid = ""
        },
      ]
      Version = "2008-10-17"
    }
  )
  force_detach_policies = false
  managed_policy_arns = [
    "arn:aws:iam::aws:policy/SecretsManagerReadWrite",
    "arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceforEC2Role",
  ]
  max_session_duration = 3600
  name                 = "EMR_EC2_DefaultRole"
  path                 = "/"
  tags                 = {}
  tags_all             = {}
}
