# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# ../../scripts/052-get-iam-attached-role-policies.sh
# aws_iam_role_policy_attachment.r-EMR_EC2_DefaultRole__AmazonElasticMapReduceforEC2Role:
resource "aws_iam_role_policy_attachment" "r-EMR_EC2_DefaultRole__AmazonElasticMapReduceforEC2Role" {
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceforEC2Role"
  role       = aws_iam_role.r-EMR_EC2_DefaultRole.id
}
