# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_security_group_rule.sg-0a61523b138dcbaf8_egress_1:
resource "aws_security_group_rule" "sg-0a61523b138dcbaf8_egress_1" {
  cidr_blocks = [
    "0.0.0.0/0",
  ]
  type              = "egress"
  from_port         = 0
  to_port           = 0
  protocol          = "-1"
  prefix_list_ids   = []
  security_group_id = aws_security_group.sg-0a61523b138dcbaf8.id
}
