# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_security_group_rule.sg-0ae136d33533aae3d_ingress_5:
resource "aws_security_group_rule" "sg-0ae136d33533aae3d_ingress_5" {
  from_port         = 5439
  prefix_list_ids   = []
  protocol          = "tcp"
  security_group_id = aws_security_group.sg-0ae136d33533aae3d.id
  self              = true
  to_port           = 5439
  type              = "ingress"
}
