# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_eip.eipalloc-0ceb35a1533829354:
resource "aws_eip" "eipalloc-0ceb35a1533829354" {
  network_border_group = "us-west-2"
  public_ipv4_pool     = "amazon"
  tags = {
    "Name" = "DE-2-1-eip-us-west-2a"
  }
  tags_all = {
    "Name" = "DE-2-1-eip-us-west-2a"
  }
  #(09.05) FIXME deprecated vpc option
  # vpc = true
  domain = "vpc"
}
