# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_security_group_rule.sg-0c5dc574de179c7a2_egress_1:
resource "aws_security_group_rule" "sg-0c5dc574de179c7a2_egress_1" {
  description              = "Rule to allow connections to de-2-1-postgres from any instances this security group is attached to"
  from_port                = 5432
  prefix_list_ids          = []
  protocol                 = "tcp"
  security_group_id        = aws_security_group.sg-0c5dc574de179c7a2.id
  source_security_group_id = aws_security_group.sg-07fc5b30fcefc6bc0.id
  to_port                  = 5432
  type                     = "egress"
}
