# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_nat_gateway.nat-0323de7ff8ad4c1a1:
resource "aws_nat_gateway" "nat-0323de7ff8ad4c1a1" {
  allocation_id     = aws_eip.eipalloc-0ceb35a1533829354.id
  connectivity_type = "public"
  subnet_id         = aws_subnet.subnet-0eaeed36de733a9ff.id
  tags = {
    "Name" = "DE-2-1-nat-public1-us-west-2a"
  }
  tags_all = {
    "Name" = "DE-2-1-nat-public1-us-west-2a"
  }
}
