# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_security_group.sg-07d5717ff00eb8f3f:
resource "aws_security_group" "sg-07d5717ff00eb8f3f" {
  description = "Master group for Elastic MapReduce created on 2023-08-22T15:23:40.320Z"
  tags = {
    "for-use-with-amazon-emr-managed-policies" = "true"
  }
  tags_all = {
    "for-use-with-amazon-emr-managed-policies" = "true"
  }
  vpc_id = aws_vpc.vpc-07f1d11942c14d8a5.id
}
