# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_security_group.sg-028b085b506695897:
resource "aws_security_group" "sg-072d3f5641460e8b5" {
  description = "default VPC security group"
  tags        = {
      "Team" = "DE-2-1"
  }
  tags_all    = {
      "Team" = "DE-2-1"
  }
  vpc_id = aws_vpc.vpc-07f1d11942c14d8a5.id
}
