# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.subnet-02fa7ecfdea40408e__rtbassoc-0e791a8d96167e2d9:
resource "aws_route_table_association" "subnet-02fa7ecfdea40408e__rtbassoc-0e791a8d96167e2d9" {
  route_table_id = aws_route_table.rtb-013b0aac9d2b3c14c.id
  subnet_id      = aws_subnet.subnet-02fa7ecfdea40408e.id
}
