# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_instance.i-0ed1023e3403a55bd:
resource "aws_instance" "i-0ed1023e3403a55bd" {
  ami                                  = "ami-03d8c6f76823576b3"
  associate_public_ip_address          = true
  availability_zone                    = "us-west-2a"
  disable_api_stop                     = false
  disable_api_termination              = false
  ebs_optimized                        = false
  get_password_data                    = false
  hibernation                          = false
  iam_instance_profile                 = aws_iam_instance_profile.EMR_EC2_DefaultRole.id
  instance_initiated_shutdown_behavior = "terminate"
  instance_type                        = "m4.large"
  key_name                             = "DE-2-1-key"
  monitoring                           = false
  placement_partition_number           = 0
  secondary_private_ips                = []
  security_groups                      = []
  source_dest_check                    = true
  subnet_id                            = aws_subnet.subnet-03a832fb5b39f193e.id
  tags = {
    "Team" = "DE-2-1"
  }
  tags_all = {
    "Team" = "DE-2-1"
  }
  tenancy = "default"
  lifecycle {
    ignore_changes = [user_data_replace_on_change, associate_public_ip_address, user_data, user_data_base64]
  }
  user_data_base64 = filebase64sha256("i-0ed1023e3403a55bd.sh")
  vpc_security_group_ids = [
    aws_security_group.sg-00f8aed2039c9e343.id,
  ]

  capacity_reservation_specification {
    capacity_reservation_preference = "open"
  }

  cpu_options {
    core_count       = 1
    threads_per_core = 2
  }

  ebs_block_device {
    delete_on_termination = true
    device_name           = "/dev/sdb"
    encrypted             = false
    iops                  = 100
    tags = {
      "Team" = "DE-2-1"
    }
    throughput  = 0
    volume_size = 32
    volume_type = "gp2"
  }

  enclave_options {
    enabled = false
  }

  maintenance_options {
    auto_recovery = "default"
  }

  metadata_options {
    http_endpoint               = "enabled"
    http_put_response_hop_limit = 1
    http_tokens                 = "optional"
    instance_metadata_tags      = "disabled"
  }

  private_dns_name_options {
    enable_resource_name_dns_a_record    = false
    enable_resource_name_dns_aaaa_record = false
    hostname_type                        = "ip-name"
  }

  root_block_device {
    delete_on_termination = true
    encrypted             = false
    iops                  = 100
    tags = {
      "Team" = "DE-2-1"
    }
    throughput  = 0
    volume_size = 15
    volume_type = "gp2"
  }
  user_data_replace_on_change = false
}
