# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table.rtb-060aa4af6214a2147:
resource "aws_route_table" "rtb-060aa4af6214a2147" {
  propagating_vgws = []
  route = [
    {
      carrier_gateway_id         = ""
      cidr_block                 = "0.0.0.0/0"
      core_network_arn           = ""
      destination_prefix_list_id = ""
      egress_only_gateway_id     = ""
      gateway_id                 = aws_internet_gateway.igw-004c760b24a787b60.id
      instance_id                = null
      ipv6_cidr_block            = null
      local_gateway_id           = ""
      nat_gateway_id             = ""
      network_interface_id       = ""
      transit_gateway_id         = ""
      vpc_endpoint_id            = ""
      vpc_peering_connection_id  = ""
    },
  ]
  tags = {
    "Name" = "DE-2-1-rtb-private1-us-west-2a"
  }
  tags_all = {
    "Name" = "DE-2-1-rtb-private1-us-west-2a"
  }
  vpc_id = aws_vpc.vpc-07f1d11942c14d8a5.id
}
