# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_security_group.sg-0a61523b138dcbaf8:
resource "aws_security_group" "sg-0a61523b138dcbaf8" {
  description = "Slave group for Elastic MapReduce created on 2023-08-23T08:06:07.453Z"
  tags = {
    "for-use-with-amazon-emr-managed-policies" = "true"
  }
  tags_all = {
    "for-use-with-amazon-emr-managed-policies" = "true"
  }
  vpc_id = aws_vpc.vpc-07f1d11942c14d8a5.id
}
