# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_vpc.vpc-07f1d11942c14d8a5:
resource "aws_vpc" "vpc-07f1d11942c14d8a5" {
  assign_generated_ipv6_cidr_block     = false
  cidr_block                           = "10.21.0.0/16"
  enable_dns_hostnames                 = true
  enable_dns_support                   = true
  enable_network_address_usage_metrics = false
  instance_tenancy                     = "default"
  tags = {
    "Name" = "DE-2-1"
    "Team" = "DE-2-1"
  }
  tags_all = {
    "Name" = "DE-2-1"
    "Team" = "DE-2-1"
  }
}
