# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_subnet.subnet-0e29f3d0e936ffd0b:
resource "aws_subnet" "subnet-0e29f3d0e936ffd0b" {
  assign_ipv6_address_on_creation                = false
  availability_zone                              = "us-west-2c"
  cidr_block                                     = "10.21.16.0/20"
  enable_dns64                                   = false
  enable_resource_name_dns_a_record_on_launch    = false
  enable_resource_name_dns_aaaa_record_on_launch = false
  ipv6_native                                    = false
  map_public_ip_on_launch                        = false
  private_dns_hostname_type_on_launch            = "ip-name"
  tags = {
    "Name" = "DE-2-1-subnet-public2-us-west-2c"
  }
  tags_all = {
    "Name" = "DE-2-1-subnet-public2-us-west-2c"
  }
  vpc_id = aws_vpc.vpc-07f1d11942c14d8a5.id
}
