# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.subnet-0eaeed36de733a9ff__rtbassoc-07f9fdf0183720d53:
resource "aws_route_table_association" "subnet-0eaeed36de733a9ff__rtbassoc-07f9fdf0183720d53" {
  route_table_id = aws_route_table.rtb-0d6f34dd37a024a0d.id
  subnet_id      = aws_subnet.subnet-0eaeed36de733a9ff.id
}
