# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.subnet-03a832fb5b39f193e__rtbassoc-0e48f79269d23f0a7:
resource "aws_route_table_association" "subnet-03a832fb5b39f193e__rtbassoc-0e48f79269d23f0a7" {
  route_table_id = aws_route_table.rtb-060aa4af6214a2147.id
  subnet_id      = aws_subnet.subnet-03a832fb5b39f193e.id
}
