# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_security_group.sg-0ae136d33533aae3d:
resource "aws_security_group" "sg-0ae136d33533aae3d" {
  description = "BastionHostSG created 2023-08-14T17:07:39.666Z"
  tags = {
    "Team" = "DE-2-1"
  }
  tags_all = {
    "Team" = "DE-2-1"
  }
  vpc_id = aws_vpc.vpc-07f1d11942c14d8a5.id
}
