# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_security_group_rule.sg-028b085b506695897_ingress_1:
resource "aws_security_group_rule" "sg-028b085b506695897_ingress_1" {
  from_port                = 9443
  prefix_list_ids          = []
  protocol                 = "tcp"
  security_group_id        = aws_security_group.sg-028b085b506695897.id
  source_security_group_id = aws_security_group.sg-0f6fa2e642162ce45.id
  to_port                  = 9443
  type                     = "ingress"
}
