# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_security_group.sg-0c5dc574de179c7a2:
resource "aws_security_group" "sg-0c5dc574de179c7a2" {
  description = "Security group attached to instances to securely connect to de-2-1-postgres. Modification could lead to connection loss."
  tags        = {}
  tags_all    = {}
  vpc_id      = aws_vpc.vpc-07f1d11942c14d8a5.id
}
