# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_security_group_rule.sg-072d3f5641460e8b5_ingress_5:
resource "aws_security_group_rule" "sg-072d3f5641460e8b5_ingress_5" {
  cidr_blocks = [
    "192.168.219.101/32",
  ]
  description       = "sh"
  from_port         = 0
  prefix_list_ids   = []
  protocol          = "tcp"
  security_group_id = aws_security_group.sg-072d3f5641460e8b5.id
  to_port           = 65535
  type              = "ingress"
}
