# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_secretsmanager_secret_version.arn_aws_secretsmanager_us-west-2_862327261051_secret_DE-2-1-SECRET-T7uW5a__v-0ca41fe1-ff0a-430c-ba8a-0b7dd2376df8:
resource "aws_secretsmanager_secret_version" "arn_aws_secretsmanager_us-west-2_862327261051_secret_DE-2-1-SECRET-T7uW5a__v-0ca41fe1-ff0a-430c-ba8a-0b7dd2376df8" {
  lifecycle {
    ignore_changes = [secret_string]
  }
  secret_id     = "arn:aws:secretsmanager:us-west-2:862327261051:secret:DE-2-1-SECRET-T7uW5a"
  secret_string = "{\"ig_user_id\":\"17841461266491372\",\"access_token\":\"removed\",\"bucket\":\"de-2-1-s3\",\"config_file\":\"configure.ini\",\"airflow_user\":\"airflow\",\"airflow_password\":\"removed\",\"redshift_conn_url\":\"jdbc:redshift://de-2-1-redshift.cpsvlqgwrfc4.us-west-2.redshift.amazonaws.com:5439/dev?user=removed&password=removed\"}"
  version_stages = [
    "AWSCURRENT",xw
  ]
}
