CREATE SCHEMA ADHOC;
CREATE SCHEMA ANALYTICS;
CREATE SCHEMA RAW_DATA;
CREATE SCHEMA META;


CREATE TABLE RAW_DATA.BRAND (
	USER_ID VARCHAR(30) NOT NULL UNIQUE,
	USER_NAME VARCHAR(50) NOT NULL,
	TAG_NAME VARCHAR(20) NOT NULL,
	NAME VARCHAR(100),
	PROFILE_PICTURE_URL VARCHAR(1000),
	FOLLOWERS_COUNT INTEGER NOT NULL DEFAULT 0,
	MEDIA_COUNT INTEGER NOT NULL DEFAULT 0,
	DEL_YN VARCHAR(1) NOT NULL DEFAULT 'Y',
	UPDATED_AT TIMESTAMP NOT NULL,
	PRIMARY KEY (USER_ID)
);

CREATE TABLE RAW_DATA.BRAND_LOG (
    user_id VARCHAR(30) NOT NULL,
    followers_count INTEGER NOT NULL DEFAULT 0,
    media_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES RAW_DATA.BRAND (user_id)
);

CREATE TABLE RAW_DATA.MEDIA (
    media_id VARCHAR(30) NOT NULL UNIQUE,
    user_id VARCHAR(30) NOT NULL,
    like_count INTEGER NOT NULL DEFAULT 0,
    comments_count INTEGER NOT NULL DEFAULT 0,
    media_product_type VARCHAR(10) NOT NULL,
    media_type VARCHAR(20) NOT NULL,
    caption VARCHAR(5000),
    permalink VARCHAR(100),
    media_url VARCHAR(1000),
    ts TIMESTAMP NOT NULL,
    del_yn CHAR(1) NOT NULL DEFAULT 'Y',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL,
    PRIMARY KEY (media_id),
    FOREIGN KEY (user_id) REFERENCES RAW_DATA.BRAND (user_id)
);

CREATE TABLE RAW_DATA.MEDIA_LOG (
    media_id VARCHAR(30) NOT NULL,
    user_id VARCHAR(30) NOT NULL,
    like_count INTEGER NOT NULL DEFAULT 0,
    comments_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (media_id) REFERENCES RAW_DATA.MEDIA (media_id),
    FOREIGN KEY (user_id) REFERENCES RAW_DATA.BRAND (user_id)
);


CREATE TABLE RAW_DATA.MEDIA_HASHTAG (
    user_id VARCHAR(30) NOT NULL,
    media_id VARCHAR(30) NOT NULL,
    media_type VARCHAR(20) NOT NULL,
    caption VARCHAR(5000),
    comments_count INTEGER NOT NULL DEFAULT 0,
    like_count INTEGER NOT NULL DEFAULT 0,
    ts TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES RAW_DATA.BRAND (user_id)
);
