# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# ../../scripts/052-get-iam-attached-role-policies.sh
# aws_iam_role_policy_attachment.r-DE-2-1-lambda-slack-role-7s4kioa1__AWSLambdaBasicExecutionRole-a5d17f78-d989-470f-aa7d-cac9f970612a:
resource "aws_iam_role_policy_attachment" "r-DE-2-1-lambda-slack-role-7s4kioa1__AWSLambdaBasicExecutionRole-a5d17f78-d989-470f-aa7d-cac9f970612a" {
  policy_arn = aws_iam_policy.p_AWSLambdaBasicExecutionRole-a5d17f78-d989-470f-aa7d-cac9f970612a.arn
  role       = aws_iam_role.r-DE-2-1-lambda-slack-role-7s4kioa1.id
}
