# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# ../../scripts/get-iam-policies.sh
# aws_iam_policy.p_AWSLambdaBasicExecutionRole-05e82a84-de6b-4132-8178-f95f56a8ba53:
resource "aws_iam_policy" "p_AWSLambdaBasicExecutionRole-05e82a84-de6b-4132-8178-f95f56a8ba53" {
  name = "AWSLambdaBasicExecutionRole-05e82a84-de6b-4132-8178-f95f56a8ba53"
  path = "/service-role/"
  policy = jsonencode(
    {
      Statement = [
        {
          Action     = "logs:CreateLogGroup"
          Effect     = "Allow"
          "Resource" = "arn:aws:logs:us-west-2:862327261051:*"
        },
        {
          Action = [
            "logs:CreateLogStream",
            "logs:PutLogEvents",
          ]
          Effect = "Allow"
          "Resource" = [
            format("arn:aws:logs:%s:%s:log-group:/aws/lambda/DE-2-1-extract-accounts:*", data.aws_region.current.name, data.aws_caller_identity.current.account_id),
          ]
        },
      ]
      Version = "2012-10-17"
    }
  )
  tags     = {}
  tags_all = {}
}
