# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role.r-DE-2-1-lambda-slack-role-7s4kioa1:
resource "aws_iam_role" "r-DE-2-1-lambda-slack-role-7s4kioa1" {
  assume_role_policy = jsonencode(
    {
      Statement = [
        {
          Action = "sts:AssumeRole"
          Effect = "Allow"
          Principal = {
            Service = "lambda.amazonaws.com"
          }
        },
      ]
      Version = "2012-10-17"
    }
  )
  force_detach_policies = false
  managed_policy_arns = [
    format("arn:aws:iam::%s:policy/service-role/AWSLambdaBasicExecutionRole-a5d17f78-d989-470f-aa7d-cac9f970612a", data.aws_caller_identity.current.account_id),
  ]
  max_session_duration = 3600
  name                 = "DE-2-1-lambda-slack-role-7s4kioa1"
  path                 = "/service-role/"
  tags                 = {}
  tags_all             = {}
}
