# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# ../../scripts/052-get-iam-attached-role-policies.sh
# aws_iam_role_policy_attachment.r-DE-2-1-extract-accounts-role-iev8xb5d__AWSLambdaLambdaFunctionDestinationExecutionRole-04b1b3f2-4439-4034-a690-bd2551af54c4:
resource "aws_iam_role_policy_attachment" "r-DE-2-1-extract-accounts-role-iev8xb5d__AWSLambdaLambdaFunctionDestinationExecutionRole-04b1b3f2-4439-4034-a690-bd2551af54c4" {
  policy_arn = aws_iam_policy.p_AWSLambdaLambdaFunctionDestinationExecutionRole-04b1b3f2-4439-4034-a690-bd2551af54c4.arn
  role       = aws_iam_role.r-DE-2-1-extract-accounts-role-iev8xb5d.id
}
