# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_lambda_permission.r_lambda-eeeed398-9c80-437e-98ac-9cfbdc0e88af:
resource "aws_lambda_permission" "r_lambda-eeeed398-9c80-437e-98ac-9cfbdc0e88af" {
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.DE-2-1-extract-hashtags.arn
  principal     = "events.amazonaws.com"
  source_arn    = format("arn:aws:events:%s:%s:rule/DE-2-1-extract-hashtag-job", data.aws_region.current.name, data.aws_caller_identity.current.account_id)
  statement_id  = "lambda-eeeed398-9c80-437e-98ac-9cfbdc0e88af"
}
