# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_lambda_function_event_invoke_config.arn_aws_lambda_us-west-2_862327261051_function_DE-2-1-lambda-slack__LATEST:
resource "aws_lambda_function_event_invoke_config" "arn_aws_lambda_us-west-2_862327261051_function_DE-2-1-lambda-slack__LATEST" {
  function_name                = "arn:aws:lambda:us-west-2:862327261051:function:DE-2-1-lambda-slack"
  maximum_event_age_in_seconds = 120
  maximum_retry_attempts       = 2
  qualifier                    = "$LATEST"
}
