# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# ../../scripts/052-get-iam-attached-role-policies.sh
# aws_iam_role_policy_attachment.r-DE-2-1-extract-hashtags-role-50co2v0c__AWSLambdaBasicExecutionRole-e634aa43-efd9-4ea9-a539-5008422289a0:
resource "aws_iam_role_policy_attachment" "r-DE-2-1-extract-hashtags-role-50co2v0c__AWSLambdaBasicExecutionRole-e634aa43-efd9-4ea9-a539-5008422289a0" {
  policy_arn = aws_iam_policy.p_AWSLambdaBasicExecutionRole-e634aa43-efd9-4ea9-a539-5008422289a0.arn
  role       = aws_iam_role.r-DE-2-1-extract-hashtags-role-50co2v0c.id
}
