# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_lambda_permission.r_lambda-f93c9ced-3513-4254-bd57-17c5150326bd:
resource "aws_lambda_permission" "r_lambda-f93c9ced-3513-4254-bd57-17c5150326bd" {
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.DE-2-1-extract-accounts.arn
  principal     = "events.amazonaws.com"
  source_arn    = format("arn:aws:events:%s:%s:rule/DE-2-1-extract-accounts-job", data.aws_region.current.name, data.aws_caller_identity.current.account_id)
  statement_id  = "lambda-f93c9ced-3513-4254-bd57-17c5150326bd"
}
