# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# ../../scripts/get-iam-policies.sh
# aws_iam_policy.p_AWSLambdaLambdaFunctionDestinationExecutionRole-81f21d51-ee25-4476-a0da-1f72309723b4:
resource "aws_iam_policy" "p_AWSLambdaLambdaFunctionDestinationExecutionRole-81f21d51-ee25-4476-a0da-1f72309723b4" {
  name = "AWSLambdaLambdaFunctionDestinationExecutionRole-81f21d51-ee25-4476-a0da-1f72309723b4"
  path = "/service-role/"
  policy = jsonencode(
    {
      Statement = [
        {
          Action     = "lambda:InvokeFunction"
          Effect     = "Allow"
          "Resource" = "arn:aws:lambda:us-west-2:862327261051:function:DE-2-1-lambda-slack*"
        },
      ]
      Version = "2012-10-17"
    }
  )
  tags     = {}
  tags_all = {}
}
