# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_lambda_function.DE-2-1-lambda-slack:
resource "aws_lambda_function" "DE-2-1-lambda-slack" {
  architectures = [
    "x86_64",
  ]
  function_name = "DE-2-1-lambda-slack"
  handler       = "lambda_function.lambda_handler"
  lifecycle {
    ignore_changes = [filename]
  }
  filename                       = "DE-2-1-lambda-slack.zip"
  layers                         = []
  memory_size                    = 128
  package_type                   = "Zip"
  reserved_concurrent_executions = -1
  role                           = aws_iam_role.r-DE-2-1-lambda-slack-role-7s4kioa1.arn
  runtime                        = "python3.10"
  skip_destroy                   = false
  source_code_hash               = filebase64sha256("DE-2-1-lambda-slack.zip")
  tags                           = {}
  tags_all                       = {}
  timeout                        = 5

  environment {
    variables = {
      "slack_webhook" = "https://hooks.slack.com/services/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"
    }
  }

  ephemeral_storage {
    size = 512
  }

  tracing_config {
    mode = "PassThrough"
  }
}
