# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# ../../scripts/052-get-iam-attached-role-policies.sh
# aws_iam_role_policy_attachment.r-DE-2-1-extract-hashtags-role-50co2v0c__AWSLambdaLambdaFunctionDestinationExecutionRole-81f21d51-ee25-4476-a0da-1f72309723b4:
resource "aws_iam_role_policy_attachment" "r-DE-2-1-extract-hashtags-role-50co2v0c__AWSLambdaLambdaFunctionDestinationExecutionRole-81f21d51-ee25-4476-a0da-1f72309723b4" {
  policy_arn = aws_iam_policy.p_AWSLambdaLambdaFunctionDestinationExecutionRole-81f21d51-ee25-4476-a0da-1f72309723b4.arn
  role       = aws_iam_role.r-DE-2-1-extract-hashtags-role-50co2v0c.id
}
