# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# ../../scripts/052-get-iam-attached-role-policies.sh
# aws_iam_role_policy_attachment.r-DE-2-1-extract-accounts-role-iev8xb5d__AWSLambdaBasicExecutionRole-05e82a84-de6b-4132-8178-f95f56a8ba53:
resource "aws_iam_role_policy_attachment" "r-DE-2-1-extract-accounts-role-iev8xb5d__AWSLambdaBasicExecutionRole-05e82a84-de6b-4132-8178-f95f56a8ba53" {
  policy_arn = aws_iam_policy.p_AWSLambdaBasicExecutionRole-05e82a84-de6b-4132-8178-f95f56a8ba53.arn
  role       = aws_iam_role.r-DE-2-1-extract-accounts-role-iev8xb5d.id
}
